// <auto-generated />
using System;
using Frock_backend.shared.Infrastructure.Persistences.EFC.Configuration;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Frock_backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260611004859_TripStatusEnum")]
    partial class TripStatusEnum
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Frock_backend.Collections.Domain.Model.Aggregates.Collection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<int>("FkIdUser")
                        .HasColumnType("int")
                        .HasColumnName("fk_id_user");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("p_k_collections");

                    b.HasIndex("FkIdUser")
                        .HasDatabaseName("i_x_collections_fk_id_user");

                    b.ToTable("collections", (string)null);
                });

            modelBuilder.Entity("Frock_backend.Collections.Domain.Model.Aggregates.CollectionItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("added_at");

                    b.Property<int>("FkIdCollection")
                        .HasColumnType("int")
                        .HasColumnName("fk_id_collection");

                    b.Property<int>("FkIdRoute")
                        .HasColumnType("int")
                        .HasColumnName("fk_id_route");

                    b.HasKey("Id")
                        .HasName("p_k_collection_items");

                    b.HasIndex("FkIdCollection")
                        .HasDatabaseName("i_x_collection_items_fk_id_collection");

                    b.HasIndex("FkIdRoute")
                        .HasDatabaseName("i_x_collection_items_fk_id_route");

                    b.ToTable("collection_items", (string)null);
                });

            modelBuilder.Entity("Frock_backend.Driver.Domain.Model.Aggregates.Driver", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("DocumentNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("document_number");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)")
                        .HasColumnName("first_name");

                    b.Property<int>("FkIdUser")
                        .HasColumnType("int")
                        .HasColumnName("fk_id_user");

                    b.Property<bool>("IsAvailable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true)
                        .HasColumnName("is_available");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)")
                        .HasColumnName("last_name");

                    b.Property<string>("LicenseCategory")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("license_category");

                    b.Property<string>("LicenseNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("license_number");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("phone");

                    b.Property<string>("PhotoUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("photo_url");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_drivers");

                    b.ToTable("drivers", (string)null);
                });

            modelBuilder.Entity("Frock_backend.Driver.Domain.Model.Aggregates.RouteDuration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int>("EstimatedMinutes")
                        .HasColumnType("int")
                        .HasColumnName("estimated_minutes");

                    b.Property<int>("FkIdRoute")
                        .HasColumnType("int")
                        .HasColumnName("fk_id_route");

                    b.Property<int>("FkIdTariff")
                        .HasColumnType("int")
                        .HasColumnName("fk_id_tariff");

                    b.HasKey("Id")
                        .HasName("p_k_route_durations");

                    b.ToTable("route_durations", (string)null);
                });

            modelBuilder.Entity("Frock_backend.Driver.Domain.Model.Aggregates.Tariff", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<decimal>("BaseFare")
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("base_fare");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("varchar(3)")
                        .HasColumnName("currency");

                    b.Property<int>("FkIdDriver")
                        .HasColumnType("int")
                        .HasColumnName("fk_id_driver");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<decimal>("MinFare")
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("min_fare");

                    b.Property<decimal>("PricePerKm")
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("price_per_km");

                    b.Property<decimal>("PricePerMinute")
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("price_per_minute");

                    b.Property<string>("WeeklyAvailability")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("available_days");

                    b.HasKey("Id")
                        .HasName("p_k_tariffs");

                    b.ToTable("tariffs", (string)null);
                });

            modelBuilder.Entity("Frock_backend.IAM.Domain.Model.Aggregates.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("email");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("password_hash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("role");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("p_k_users");

                    b.ToTable("users");
                });

            modelBuilder.Entity("Frock_backend.Notifications.Domain.Model.Aggregates.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<int>("FkIdUser")
                        .HasColumnType("int")
                        .HasColumnName("fk_id_user");

                    b.Property<bool>("IsRead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false)
                        .HasColumnName("is_read");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("message");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("title");

                    b.Property<string>("Type")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("Info")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("p_k_notifications");

                    b.HasIndex("FkIdUser")
                        .HasDatabaseName("i_x_notifications_fk_id_user");

                    b.ToTable("notifications", (string)null);
                });

            modelBuilder.Entity("Frock_backend.Payments.Domain.Model.Aggregates.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTime?>("ConfirmedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("confirmed_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("ExternalReference")
                        .HasColumnType("longtext")
                        .HasColumnName("external_reference");

                    b.Property<int>("FkIdUser")
                        .HasColumnType("int")
                        .HasColumnName("fk_id_user");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("method");

                    b.Property<int>("ReferenceId")
                        .HasColumnType("int")
                        .HasColumnName("reference_id");

                    b.Property<string>("ReferenceType")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("reference_type");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("p_k_payments");

                    b.ToTable("payments", (string)null);
                });

            modelBuilder.Entity("Frock_backend.Payments.Domain.Model.Aggregates.Refund", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTime?>("ConfirmedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("confirmed_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<int>("FkIdPayment")
                        .HasColumnType("int")
                        .HasColumnName("fk_id_payment");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("reason");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("p_k_refunds");

                    b.HasIndex("FkIdPayment")
                        .HasDatabaseName("i_x_refunds_fk_id_payment");

                    b.ToTable("refunds", (string)null);
                });

            modelBuilder.Entity("Frock_backend.Ratings.Domain.Model.Aggregates.Rating", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Comment")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("comment");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<int>("FkIdDriver")
                        .HasColumnType("int")
                        .HasColumnName("fk_id_driver");

                    b.Property<int>("FkIdTrip")
                        .HasColumnType("int")
                        .HasColumnName("fk_id_trip");

                    b.Property<int>("FkIdUser")
                        .HasColumnType("int")
                        .HasColumnName("fk_id_user");

                    b.Property<int>("Score")
                        .HasColumnType("int")
                        .HasColumnName("score");

                    b.HasKey("Id")
                        .HasName("p_k_ratings");

                    b.HasIndex("FkIdDriver")
                        .HasDatabaseName("i_x_ratings_fk_id_driver");

                    b.HasIndex("FkIdUser")
                        .HasDatabaseName("i_x_ratings_fk_id_user");

                    b.ToTable("ratings", (string)null);
                });

            modelBuilder.Entity("Frock_backend.Subscriptions.Domain.Model.Aggregates.Plan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Benefits")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("benefits");

                    b.Property<string>("BillingCycle")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("billing_cycle");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("varchar(3)")
                        .HasColumnName("currency");

                    b.Property<int?>("DiscoveryQuota")
                        .HasColumnType("int")
                        .HasColumnName("discovery_quota");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.Property<string>("PlanType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("plan_type");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("price");

                    b.Property<string>("TargetRole")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("target_role");

                    b.HasKey("Id")
                        .HasName("p_k_plans");

                    b.ToTable("plans", (string)null);
                });

            modelBuilder.Entity("Frock_backend.Subscriptions.Domain.Model.Aggregates.Subscription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<bool>("AutoRenew")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("auto_renew");

                    b.Property<int>("DiscoveryUsageInCycle")
                        .HasColumnType("int")
                        .HasColumnName("discovery_usage_in_cycle");

                    b.Property<DateTime>("EndsAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("ends_at");

                    b.Property<int?>("FkIdPayment")
                        .HasColumnType("int")
                        .HasColumnName("fk_id_payment");

                    b.Property<int>("FkIdPlan")
                        .HasColumnType("int")
                        .HasColumnName("fk_id_plan");

                    b.Property<int>("FkIdUser")
                        .HasColumnType("int")
                        .HasColumnName("fk_id_user");

                    b.Property<DateTime>("StartsAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("starts_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("p_k_subscriptions");

                    b.ToTable("subscriptions", (string)null);
                });

            modelBuilder.Entity("Frock_backend.Trips.Domain.Model.Aggregates.Reservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTime?>("ConfirmedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("confirmed_at");

                    b.Property<string>("DocumentNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("document_number");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("document_type");

                    b.Property<int?>("FkIdPayment")
                        .HasColumnType("int")
                        .HasColumnName("fk_id_payment");

                    b.Property<int>("FkIdTrip")
                        .HasColumnType("int")
                        .HasColumnName("fk_id_trip");

                    b.Property<int>("FkIdUser")
                        .HasColumnType("int")
                        .HasColumnName("fk_id_user");

                    b.Property<DateTime>("ReservedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("reserved_at");

                    b.Property<int>("Seats")
                        .HasColumnType("int")
                        .HasColumnName("seats");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("p_k_reservations");

                    b.HasIndex("FkIdTrip")
                        .HasDatabaseName("i_x_reservations_fk_id_trip");

                    b.ToTable("reservations", (string)null);
                });

            modelBuilder.Entity("Frock_backend.Trips.Domain.Model.Aggregates.Trip", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int>("AvailableSeats")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("available_seats");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("end_time");

                    b.Property<int>("FkIdDestinationStop")
                        .HasColumnType("int")
                        .HasColumnName("fk_id_destination_stop");

                    b.Property<int?>("FkIdDriver")
                        .HasColumnType("int")
                        .HasColumnName("fk_id_driver");

                    b.Property<int>("FkIdOriginStop")
                        .HasColumnType("int")
                        .HasColumnName("fk_id_origin_stop");

                    b.Property<int>("FkIdRoute")
                        .HasColumnType("int")
                        .HasColumnName("fk_id_route");

                    b.Property<int>("FkIdUser")
                        .HasColumnType("int")
                        .HasColumnName("fk_id_user");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("price");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("start_time");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("Pending")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("p_k_trips");

                    b.HasIndex("FkIdDestinationStop")
                        .HasDatabaseName("i_x_trips_fk_id_destination_stop");

                    b.HasIndex("FkIdDriver")
                        .HasDatabaseName("i_x_trips_fk_id_driver");

                    b.HasIndex("FkIdOriginStop")
                        .HasDatabaseName("i_x_trips_fk_id_origin_stop");

                    b.HasIndex("FkIdRoute")
                        .HasDatabaseName("i_x_trips_fk_id_route");

                    b.HasIndex("FkIdUser")
                        .HasDatabaseName("i_x_trips_fk_id_user");

                    b.ToTable("trips", (string)null);
                });

            modelBuilder.Entity("Frock_backend.routes.Domain.Model.Aggregates.RouteAggregate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<decimal?>("DistanceMeters")
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("distance_meters");

                    b.Property<int>("Duration")
                        .HasColumnType("int")
                        .HasColumnName("duration");

                    b.Property<int?>("DurationSeconds")
                        .HasColumnType("int")
                        .HasColumnName("duration_seconds");

                    b.Property<int>("Frequency")
                        .HasColumnType("int")
                        .HasColumnName("frequency");

                    b.Property<string>("Geometry")
                        .HasColumnType("TEXT")
                        .HasColumnName("geometry");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<double>("Price")
                        .HasColumnType("double")
                        .HasColumnName("price");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("Active")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("p_k_routes");

                    b.ToTable("routes", (string)null);
                });

            modelBuilder.Entity("Frock_backend.routes.Domain.Model.Entities.RoutesStops", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int>("FKRouteId")
                        .HasColumnType("int")
                        .HasColumnName("f_k_route_id");

                    b.Property<int>("FkStopId")
                        .HasColumnType("int")
                        .HasColumnName("fk_stop_id");

                    b.HasKey("Id")
                        .HasName("p_k_route_stops");

                    b.HasIndex("FKRouteId")
                        .HasDatabaseName("i_x_route_stops_f_k_route_id");

                    b.HasIndex("FkStopId")
                        .HasDatabaseName("i_x_route_stops_fk_stop_id");

                    b.ToTable("route_stops", (string)null);
                });

            modelBuilder.Entity("Frock_backend.routes.Domain.Model.Entities.Schedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("DayOfWeek")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("day_of_week");

                    b.Property<bool>("Enabled")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("enabled");

                    b.Property<string>("EndTime")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("end_time");

                    b.Property<int>("RouteId")
                        .HasColumnType("int")
                        .HasColumnName("route_id");

                    b.Property<string>("StartTime")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("start_time");

                    b.HasKey("Id")
                        .HasName("p_k_schedules");

                    b.HasIndex("RouteId")
                        .HasDatabaseName("i_x_schedules_route_id");

                    b.ToTable("schedules", (string)null);
                });

            modelBuilder.Entity("Frock_backend.stops.Domain.Model.Aggregates.Geographic.District", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int>("FkIdProvince")
                        .HasColumnType("int")
                        .HasColumnName("fk_id_province");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("p_k_districts");

                    b.HasIndex("FkIdProvince")
                        .HasDatabaseName("i_x_districts_fk_id_province");

                    b.ToTable("districts");
                });

            modelBuilder.Entity("Frock_backend.stops.Domain.Model.Aggregates.Geographic.Province", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int>("FkIdRegion")
                        .HasColumnType("int")
                        .HasColumnName("fk_id_region");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("p_k_provinces");

                    b.HasIndex("FkIdRegion")
                        .HasDatabaseName("i_x_provinces_fk_id_region");

                    b.ToTable("provinces");
                });

            modelBuilder.Entity("Frock_backend.stops.Domain.Model.Aggregates.Geographic.Region", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("p_k_regions");

                    b.ToTable("regions");
                });

            modelBuilder.Entity("Frock_backend.stops.Domain.Model.Aggregates.Stop", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("address");

                    b.Property<int>("FkIdDistrict")
                        .HasColumnType("int")
                        .HasColumnName("fk_id_district");

                    b.Property<int>("FkIdDriver")
                        .HasColumnType("int")
                        .HasColumnName("fk_id_driver");

                    b.Property<string>("GoogleMapsUrl")
                        .HasColumnType("longtext")
                        .HasColumnName("google_maps_url");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("longtext")
                        .HasColumnName("image_url");

                    b.Property<double?>("Latitude")
                        .HasColumnType("double")
                        .HasColumnName("latitude");

                    b.Property<double?>("Longitude")
                        .HasColumnType("double")
                        .HasColumnName("longitude");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("reference");

                    b.HasKey("Id")
                        .HasName("p_k_stops");

                    b.HasIndex("FkIdDistrict")
                        .HasDatabaseName("i_x_stops_fk_id_district");

                    b.HasIndex("FkIdDriver")
                        .HasDatabaseName("i_x_stops_fk_id_driver");

                    b.ToTable("stops");
                });

            modelBuilder.Entity("Frock_backend.Collections.Domain.Model.Aggregates.Collection", b =>
                {
                    b.HasOne("Frock_backend.IAM.Domain.Model.Aggregates.User", null)
                        .WithMany()
                        .HasForeignKey("FkIdUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_collections__user_fk_id_user");
                });

            modelBuilder.Entity("Frock_backend.Collections.Domain.Model.Aggregates.CollectionItem", b =>
                {
                    b.HasOne("Frock_backend.Collections.Domain.Model.Aggregates.Collection", null)
                        .WithMany("Items")
                        .HasForeignKey("FkIdCollection")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_collection_items_collections_fk_id_collection");

                    b.HasOne("Frock_backend.routes.Domain.Model.Aggregates.RouteAggregate", null)
                        .WithMany()
                        .HasForeignKey("FkIdRoute")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_collection_items__routes_fk_id_route");
                });

            modelBuilder.Entity("Frock_backend.Driver.Domain.Model.Aggregates.Driver", b =>
                {
                    b.OwnsOne("Frock_backend.Driver.Domain.Model.ValueObjects.Vehicle", "Vehicle", b1 =>
                        {
                            b1.Property<int>("Id")
                                .HasColumnType("int")
                                .HasColumnName("id");

                            b1.Property<string>("Brand")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("varchar(50)")
                                .HasColumnName("vehicle_brand");

                            b1.Property<int>("Capacity")
                                .HasColumnType("int")
                                .HasColumnName("vehicle_capacity");

                            b1.Property<string>("Model")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("varchar(50)")
                                .HasColumnName("vehicle_model");

                            b1.Property<string>("Plate")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("varchar(10)")
                                .HasColumnName("vehicle_plate");

                            b1.Property<string>("Type")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("varchar(20)")
                                .HasColumnName("vehicle_type");

                            b1.Property<int>("Year")
                                .HasColumnType("int")
                                .HasColumnName("vehicle_year");

                            b1.HasKey("Id")
                                .HasName("p_k_drivers");

                            b1.ToTable("drivers");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("f_k_drivers_drivers_id");
                        });

                    b.Navigation("Vehicle")
                        .IsRequired();
                });

            modelBuilder.Entity("Frock_backend.Notifications.Domain.Model.Aggregates.Notification", b =>
                {
                    b.HasOne("Frock_backend.IAM.Domain.Model.Aggregates.User", null)
                        .WithMany()
                        .HasForeignKey("FkIdUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_notifications_users_fk_id_user");
                });

            modelBuilder.Entity("Frock_backend.Payments.Domain.Model.Aggregates.Payment", b =>
                {
                    b.OwnsOne("Frock_backend.Payments.Domain.Model.ValueObjects.Money", "Amount", b1 =>
                        {
                            b1.Property<int>("Id")
                                .HasColumnType("int")
                                .HasColumnName("id");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(12,2)")
                                .HasColumnName("amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("varchar(3)")
                                .HasColumnName("currency");

                            b1.HasKey("Id")
                                .HasName("p_k_payments");

                            b1.ToTable("payments");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("f_k_payments_payments_id");
                        });

                    b.Navigation("Amount")
                        .IsRequired();
                });

            modelBuilder.Entity("Frock_backend.Payments.Domain.Model.Aggregates.Refund", b =>
                {
                    b.HasOne("Frock_backend.Payments.Domain.Model.Aggregates.Payment", null)
                        .WithMany()
                        .HasForeignKey("FkIdPayment")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("f_k_refunds_payments_fk_id_payment");

                    b.OwnsOne("Frock_backend.Payments.Domain.Model.ValueObjects.Money", "Amount", b1 =>
                        {
                            b1.Property<int>("Id")
                                .HasColumnType("int")
                                .HasColumnName("id");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(12,2)")
                                .HasColumnName("amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("varchar(3)")
                                .HasColumnName("currency");

                            b1.HasKey("Id")
                                .HasName("p_k_refunds");

                            b1.ToTable("refunds");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("f_k_refunds_refunds_id");
                        });

                    b.Navigation("Amount")
                        .IsRequired();
                });

            modelBuilder.Entity("Frock_backend.Ratings.Domain.Model.Aggregates.Rating", b =>
                {
                    b.HasOne("Frock_backend.IAM.Domain.Model.Aggregates.User", null)
                        .WithMany()
                        .HasForeignKey("FkIdDriver")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("f_k_ratings_users_fk_id_driver");

                    b.HasOne("Frock_backend.IAM.Domain.Model.Aggregates.User", null)
                        .WithMany()
                        .HasForeignKey("FkIdUser")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("f_k_ratings_users_fk_id_user");
                });

            modelBuilder.Entity("Frock_backend.Trips.Domain.Model.Aggregates.Reservation", b =>
                {
                    b.HasOne("Frock_backend.Trips.Domain.Model.Aggregates.Trip", null)
                        .WithMany()
                        .HasForeignKey("FkIdTrip")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("f_k_reservations__trips_fk_id_trip");
                });

            modelBuilder.Entity("Frock_backend.Trips.Domain.Model.Aggregates.Trip", b =>
                {
                    b.HasOne("Frock_backend.stops.Domain.Model.Aggregates.Stop", null)
                        .WithMany()
                        .HasForeignKey("FkIdDestinationStop")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("f_k_trips__stop_fk_id_destination_stop");

                    b.HasOne("Frock_backend.IAM.Domain.Model.Aggregates.User", null)
                        .WithMany()
                        .HasForeignKey("FkIdDriver")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("f_k_trips_users_fk_id_driver");

                    b.HasOne("Frock_backend.stops.Domain.Model.Aggregates.Stop", null)
                        .WithMany()
                        .HasForeignKey("FkIdOriginStop")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("f_k_trips__stop_fk_id_origin_stop");

                    b.HasOne("Frock_backend.routes.Domain.Model.Aggregates.RouteAggregate", null)
                        .WithMany()
                        .HasForeignKey("FkIdRoute")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("f_k_trips__routes_fk_id_route");

                    b.HasOne("Frock_backend.IAM.Domain.Model.Aggregates.User", null)
                        .WithMany()
                        .HasForeignKey("FkIdUser")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("f_k_trips_users_fk_id_user");
                });

            modelBuilder.Entity("Frock_backend.routes.Domain.Model.Entities.RoutesStops", b =>
                {
                    b.HasOne("Frock_backend.routes.Domain.Model.Aggregates.RouteAggregate", "Route")
                        .WithMany("Stops")
                        .HasForeignKey("FKRouteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_route_stops_routes_f_k_route_id");

                    b.HasOne("Frock_backend.stops.Domain.Model.Aggregates.Stop", "Stop")
                        .WithMany()
                        .HasForeignKey("FkStopId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("f_k_route_stops__stop_fk_stop_id");

                    b.Navigation("Route");

                    b.Navigation("Stop");
                });

            modelBuilder.Entity("Frock_backend.routes.Domain.Model.Entities.Schedule", b =>
                {
                    b.HasOne("Frock_backend.routes.Domain.Model.Aggregates.RouteAggregate", null)
                        .WithMany("Schedules")
                        .HasForeignKey("RouteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_schedules_routes_route_id");
                });

            modelBuilder.Entity("Frock_backend.stops.Domain.Model.Aggregates.Geographic.District", b =>
                {
                    b.HasOne("Frock_backend.stops.Domain.Model.Aggregates.Geographic.Province", null)
                        .WithMany()
                        .HasForeignKey("FkIdProvince")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("f_k_districts__province_fk_id_province");
                });

            modelBuilder.Entity("Frock_backend.stops.Domain.Model.Aggregates.Geographic.Province", b =>
                {
                    b.HasOne("Frock_backend.stops.Domain.Model.Aggregates.Geographic.Region", null)
                        .WithMany()
                        .HasForeignKey("FkIdRegion")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("f_k_provinces__region_fk_id_region");
                });

            modelBuilder.Entity("Frock_backend.stops.Domain.Model.Aggregates.Stop", b =>
                {
                    b.HasOne("Frock_backend.stops.Domain.Model.Aggregates.Geographic.District", null)
                        .WithMany()
                        .HasForeignKey("FkIdDistrict")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("f_k_stops_districts_fk_id_district");

                    b.HasOne("Frock_backend.Driver.Domain.Model.Aggregates.Driver", null)
                        .WithMany()
                        .HasForeignKey("FkIdDriver")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("f_k_stops_drivers_fk_id_driver");
                });

            modelBuilder.Entity("Frock_backend.Collections.Domain.Model.Aggregates.Collection", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Frock_backend.routes.Domain.Model.Aggregates.RouteAggregate", b =>
                {
                    b.Navigation("Schedules");

                    b.Navigation("Stops");
                });
#pragma warning restore 612, 618
        }
    }
}
